/*

 BACK.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 40 x 18
   Tile set      : C:\Users\amstd\OneDrive\Desktop\gbtd22\back.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define backWidth 40
#define backHeight 18
#define backBank 0

extern unsigned char back[];

/* End of BACK.H */
