/*

 GUY.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char guy[] =
{
  0xFF,0xFF,0x81,0xFF,0xBF,0xC1,0x9B,0xD3,
  0xBF,0xC1,0xA7,0xC3,0xBE,0xC2,0xBE,0xC2,
  0xBE,0xD2,0xBE,0xD2,0xBE,0xD2,0xBE,0xD2,
  0xBE,0xD2,0xBF,0xDB,0xBF,0xC9,0xFF,0xFF
};

/* End of GUY.C */
